In [1]:
import pandas as pd

# Estructuración de los datos de ventanas de tiempo

Los conjuntos de datos tratados en este indice, sufrieron un tratamiento con el script desarrollado en el trabajo investigativo "Analysis of Time Windows to detect Botnet Behavior". Este script lo modifique, puesto que tenia algunos errores, como la falta de control de anomalias y la omicion de algunos archivos en el proceso, sin justificación.

#### Cargamos los datos benignos 
Este conjunto de datos provienen de capturas de trafico de urls del TOP 500 de Alexa. Tambien se le complemento con capturas de trafico de urls de otros tops que la misma plataforma.

In [2]:
benignoAlexa = pd.read_csv('./DATA/ALEXA_BENIGNOS/TIME/Benigno_Alexa.csv')
benignoAlexa.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,42,TCP,UDP,NaN,138.6785,193.6895,194.93300,6778.668,240.226,...,443,80.0,1900.0,4.25,7.0,8.0,178.5,256.0,312.00,not_mine
1,0-csves/1.csv,46,UDP,TCP,ICMP6,0.0000,0.1090,45.09775,784.026,93.159,...,53,80.0,34048.0,1.00,2.0,7.5,47.0,90.5,741.75,not_mine
2,1-csves/0.csv,187,TCP,UDP,NaN,0.1055,1.9840,120.20850,8454.095,210.496,...,443,80.0,123.0,3.00,9.0,15.0,80.0,696.0,1540.00,not_mine
3,1-csves/1.csv,125,TCP,UDP,NaN,0.0000,1.2800,4.41400,395.649,15.013,...,443,53.0,1900.0,1.00,10.0,14.0,56.0,827.0,1560.00,not_mine
4,2-csves/0.csv,34,TCP,UDP,NaN,0.0000,0.2210,37.53275,469.353,52.661,...,443,53.0,36262.0,1.00,4.0,7.0,65.0,160.0,255.00,not_mine

In [3]:
print(f"El conjunto de datos benigno no aleatorio inicial es de {benignoAlexa.ndim} dimensiones con {benignoAlexa.shape[0]} filas y {benignoAlexa.shape[1]} columnas")

El conjunto de datos benigno no aleatorio inicial es de 2 dimensiones con 2501 filas y 31 columnas

In [4]:
bitcash = pd.read_csv('./DATA/BITCASH/TIME/BITCASH.csv')
bitcash.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,2,TCP,NaN,NaN,0.29150,0.3090,0.32650,0.618,0.344,...,3337,54082.0,NaN,5.00,5.0,5.00,476.25,703.5,930.75,mine
1,1-csves/0.csv,2,TCP,NaN,NaN,293.50750,293.5080,293.50850,587.016,293.509,...,3337,54082.0,NaN,11.00,11.0,11.00,2584.75,4949.5,7314.25,mine
2,1-csves/1.csv,2,TCP,NaN,NaN,243.19225,243.1935,243.19475,486.387,243.196,...,3337,54082.0,NaN,15.00,15.0,15.00,2880.75,5461.5,8042.25,mine
3,1-csves/2.csv,2,TCP,NaN,NaN,264.13100,264.1320,264.13300,528.264,264.134,...,3337,54082.0,NaN,21.25,21.5,21.75,3610.75,6573.5,9536.25,mine
4,1-csves/3.csv,2,TCP,NaN,NaN,243.56325,243.5635,243.56375,487.127,243.564,...,3337,54082.0,NaN,9.00,9.0,9.00,2062.00,3944.0,5826.00,mine

In [5]:
print(f"El conjunto de datos de bitcash inicial es de {bitcash.ndim} dimensiones con {bitcash.shape[0]} filas y {bitcash.shape[1]} columnas")

El conjunto de datos de bitcash inicial es de 2 dimensiones con 485 filas y 31 columnas

In [6]:
bitcoin = pd.read_csv('./DATA/BITCOIN/TIME/BITCOIN.csv')
bitcoin.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,2,TCP,NaN,NaN,245.09100,245.0910,245.09100,490.182,245.091,...,3332,51453,NaN,17.75,19.5,21.25,3826.75,7179.5,10532.25,mine
1,0-csves/1.csv,6,TCP,NaN,NaN,122.82400,240.5955,242.30000,1134.032,242.868,...,3332,51469,51467.0,12.25,16.0,21.25,476.00,3407.0,11993.00,mine
2,0-csves/2.csv,2,TCP,NaN,NaN,242.47425,242.4745,242.47475,484.949,242.475,...,3332,51455,NaN,17.25,19.5,21.75,3814.50,7175.0,10535.50,mine
3,0-csves/3.csv,4,TCP,NaN,NaN,241.01000,241.9955,242.99850,968.052,243.051,...,3332,51435,51431.0,11.75,14.0,16.25,410.50,5978.0,11899.75,mine
4,0-csves/4.csv,2,TCP,NaN,NaN,0.12325,0.1235,0.12375,0.247,0.124,...,3332,51431,NaN,5.00,5.0,5.00,621.25,993.5,1365.75,mine

In [7]:
print(f"El conjunto de datos de bitcoin inicial es de {bitcoin.ndim} dimensiones con {bitcoin.shape[0]} filas y {bitcoin.shape[1]} columnas")

El conjunto de datos de bitcoin inicial es de 2 dimensiones con 247 filas y 31 columnas

In [8]:
litecoin = pd.read_csv('./DATA/LITECOIN/TIME/LITECOIN.csv')
litecoin.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,2,TCP,NaN,NaN,274.53550,274.5360,274.53650,549.072,274.537,...,3333,50348.0,NaN,28.75,29.5,30.25,5787.00,10639.0,15491.00,mine
1,0-csves/1.csv,2,TCP,NaN,NaN,285.28225,285.2885,285.29475,570.577,285.301,...,3333,50348.0,NaN,22.50,23.0,23.50,5209.50,9729.0,14248.50,mine
2,0-csves/2.csv,4,TCP,NaN,NaN,14.59825,118.0000,221.40300,472.005,221.412,...,3333,50348.0,NaN,2.00,9.5,17.00,265.00,650.0,3547.50,mine
3,0-csves/3.csv,2,TCP,NaN,NaN,584.41425,584.4285,584.44275,1168.857,584.457,...,3333,50348.0,NaN,41.75,43.5,45.25,8880.25,16090.5,23300.75,mine
4,0-csves/4.csv,2,TCP,NaN,NaN,325.51925,325.5375,325.55575,651.075,325.574,...,3333,50348.0,NaN,22.25,22.5,22.75,5095.50,9627.0,14158.50,mine

In [9]:
print(f"El conjunto de datos de litecoin inicial es de {litecoin.ndim} dimensiones con {litecoin.shape[0]} filas y {litecoin.shape[1]} columnas")

El conjunto de datos de litecoin inicial es de 2 dimensiones con 349 filas y 31 columnas

In [10]:
eth = pd.read_csv('./DATA/ETHERUM/TIME/ETHERUM.csv')
eth.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,2,TCP,NaN,NaN,65.96125,66.6435,67.32575,133.287,68.008,...,56525,4444.0,NaN,47.75,49.5,51.25,4440.50,6397.0,8353.50,mine
1,1-csves/1.csv,2,TCP,NaN,NaN,300.02900,300.0320,300.03500,600.064,300.038,...,56731,4444.0,NaN,186.50,189.0,191.50,16837.50,25288.0,33738.50,mine
2,1-csves/2.csv,12,TCP,NaN,NaN,28.79975,56.7100,73.71975,704.725,113.899,...,56731,4444.0,NaN,21.75,31.5,44.75,1725.00,3853.0,6352.50,mine
3,1-csves/3.csv,4,TCP,NaN,NaN,20.03200,25.0070,29.98525,100.041,30.016,...,56731,4444.0,NaN,13.50,15.5,17.50,722.75,1525.5,2735.75,mine
4,1-csves/4.csv,7,TCP,NaN,NaN,5.68250,6.5630,40.75300,174.606,75.137,...,56731,4444.0,NaN,4.00,5.0,20.00,354.00,822.0,1668.50,mine

In [11]:
print(f"El conjunto de datos ethereum  inicial es de {eth.ndim} dimensiones con {eth.shape[0]} filas y {eth.shape[1]} columnas")

El conjunto de datos ethereum  inicial es de 2 dimensiones con 959 filas y 31 columnas

In [12]:
monero = pd.read_csv('./DATA/MONERO/TIME/MONERO.csv')
monero.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,2,TCP,NaN,NaN,269.96800,269.9680,269.96800,539.936,269.968,...,51085,14444,NaN,6.0,6.0,6.00,484.50,849.0,1213.50,mine
1,0-csves/3.csv,2,TCP,NaN,NaN,497.44000,497.4400,497.44000,994.880,497.440,...,51085,14444,NaN,15.0,15.0,15.00,1211.25,2122.5,3033.75,mine
2,0-csves/4.csv,8,TCP,NaN,NaN,0.06950,0.0795,73.29725,586.342,293.003,...,14444,51083,51085.0,4.0,4.5,8.25,92.00,187.5,551.50,mine
3,1-csves/0.csv,2,TCP,NaN,NaN,526.38700,526.3870,526.38700,1052.774,526.387,...,53473,14444,NaN,16.0,16.0,16.00,1331.00,2004.0,2677.00,mine
4,1-csves/2.csv,2,TCP,NaN,NaN,275.21225,275.2125,275.21275,550.425,275.213,...,53473,14444,NaN,11.0,11.0,11.00,928.50,1299.0,1669.50,mine

In [13]:
print(f"El conjunto de monero  inicial es de {monero.ndim} dimensiones con {monero.shape[0]} filas y {monero.shape[1]} columnas")

El conjunto de monero  inicial es de 2 dimensiones con 192 filas y 31 columnas

In [14]:
sinclasificar = pd.read_csv('./DATA/SIN_CLASIFICAR/TIME/Minero_sin_clasificar.csv')
sinclasificar.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,first_dp,second_dp,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type
0,0-csves/0.csv,1564,TCP,UDP,ICMP,0.00,0.1010,1.72100,10701.930,177.706,...,53,443.0,80.0,1.0,2.0,16.0,40.00,115.5,1883.50,mine
1,0-csves/1.csv,50572,TCP,UDP,NaN,0.12,0.1210,0.12400,11602.090,55.906,...,53,443.0,80.0,2.0,2.0,2.0,40.00,63.0,88.00,mine
2,1-csves/0.csv,2,TCP,NaN,NaN,366.69,366.7300,366.77000,733.460,366.810,...,443,49270.0,NaN,30.0,33.0,36.0,3988.00,5962.0,7936.00,mine
3,1-csves/1.csv,20,TCP,UDP,NaN,0.00,4.1530,7.70100,86.786,12.255,...,443,53.0,62357.0,1.0,12.5,17.5,50.75,798.0,7411.50,mine
4,2-csves/0.csv,322,TCP,UDP,NaN,0.00,1.9585,27.59625,6541.874,303.171,...,443,5355.0,53.0,1.0,5.0,11.0,50.00,316.0,2281.25,mine

In [15]:
print(f"El conjunto de datos de mineros sin clasificar inicial es de {sinclasificar.ndim} dimensiones con {sinclasificar.shape[0]} filas y {sinclasificar.shape[1]} columnas")

El conjunto de datos de mineros sin clasificar inicial es de 2 dimensiones con 37053 filas y 31 columnas

Asignamos una columna 'Cryptocurrency' y 'Id_Cryptocurrency' para representar el tipo de criptomoneda, ya que concatenaremos los conjunto de datos mineros y el conjunto de trafico no minero.

In [16]:
benignoAlexa['Cryptocurrency'] = None
benignoAlexa['Id_Cryptocurrency'] = 0
bitcoin['Cryptocurrency'] = 'Bitcoin'
bitcoin['Id_Cryptocurrency'] = 1
bitcash['Cryptocurrency'] = 'Bitcash'
bitcash['Id_Cryptocurrency'] = 2
litecoin['Cryptocurrency'] = 'Litecoin'
litecoin['Id_Cryptocurrency'] = 3
eth['Cryptocurrency'] = 'Etherium'
eth['Id_Cryptocurrency'] = 4
monero['Cryptocurrency'] = 'Monero'
monero['Id_Cryptocurrency'] = 5
sinclasificar['Cryptocurrency'] = 'Unclassified'
sinclasificar['Id_Cryptocurrency'] = 6

### Estructuración data benigna con data minera pura

In [17]:
pure_data_miner = pd.concat([bitcoin,bitcash,litecoin,eth,monero,benignoAlexa], axis=0)

In [18]:
pure_data_miner.head()

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type,Cryptocurrency,Id_Cryptocurrency
0,0-csves/0.csv,2,TCP,NaN,NaN,245.09100,245.0910,245.09100,490.182,245.091,...,NaN,17.75,19.5,21.25,3826.75,7179.5,10532.25,mine,Bitcoin,1
1,0-csves/1.csv,6,TCP,NaN,NaN,122.82400,240.5955,242.30000,1134.032,242.868,...,51467.0,12.25,16.0,21.25,476.00,3407.0,11993.00,mine,Bitcoin,1
2,0-csves/2.csv,2,TCP,NaN,NaN,242.47425,242.4745,242.47475,484.949,242.475,...,NaN,17.25,19.5,21.75,3814.50,7175.0,10535.50,mine,Bitcoin,1
3,0-csves/3.csv,4,TCP,NaN,NaN,241.01000,241.9955,242.99850,968.052,243.051,...,51431.0,11.75,14.0,16.25,410.50,5978.0,11899.75,mine,Bitcoin,1
4,0-csves/4.csv,2,TCP,NaN,NaN,0.12325,0.1235,0.12375,0.247,0.124,...,NaN,5.00,5.0,5.00,621.25,993.5,1365.75,mine,Bitcoin,1

In [19]:
pure_data_miner.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500],
           dtype='int64', length=4733)

In [20]:
print(f"El dataset estructurado inicial es de {pure_data_miner.ndim} dimensiones con {pure_data_miner.shape[0]} filas y {pure_data_miner.shape[1]} columnas")

El dataset estructurado inicial es de 2 dimensiones con 4733 filas y 33 columnas

In [21]:
# Resetie los indices del dataframe, para que no apunte un mismo indice a varios registros
pure_data_miner = pure_data_miner.reset_index()

In [22]:
# Genere un rango de valores
indices = list(range(0,len(pure_data_miner.index)))
import random
# El rango de valores se le aplico aleatoriedad de manera pseudoaleatorio
random.shuffle(indices)

In [23]:
# Introduje aleatoriedad al conjunto de datos con el rango de indices 
pure_data_miner = pure_data_miner.reindex(indices)
pure_data_miner

,index,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,...,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type,Cryptocurrency,Id_Cryptocurrency
481,234,38-csves/4.csv,2,TCP,NaN,NaN,285.35925,285.3865,285.41375,570.773,...,NaN,17.25,17.5,17.75,3665.75,6866.5,10067.25,mine,Bitcash,2
3403,1171,602-csves/1.csv,145,TCP,UDP,NaN,0.00000,0.0320,45.09200,3319.648,...,80.0,1.00,2.0,10.00,37.00,64.0,1555.00,not_mine,None,0
4125,1893,971-csves/0.csv,176,TCP,UDP,NaN,0.00000,0.0000,13.33525,1790.951,...,80.0,1.00,1.0,3.00,32.00,64.0,132.75,not_mine,None,0
79,79,13-csves/1.csv,2,TCP,NaN,NaN,196.18225,196.1895,196.19675,392.379,...,NaN,10.50,11.0,11.50,2679.50,5159.0,7638.50,mine,Bitcoin,1
2644,412,211-csves/1.csv,57,TCP,UDP,NaN,89.52900,148.0000,180.00700,6699.510,...,80.0,4.00,5.0,7.00,100.00,192.0,280.00,not_mine,None,0
1343,262,10-csves/2.csv,2,TCP,NaN,NaN,596.68400,596.6970,596.71000,1193.394,...,NaN,323.00,335.0,347.00,30541.00,45469.0,60397.00,mine,Etherium,4
4027,1795,921-csves/1.csv,52,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,...,53600.0,1.00,1.0,1.00,39.00,56.0,103.50,not_mine,None,0
4354,2122,1089-csves/0.csv,196,TCP,UDP,NaN,42.16525,103.7895,137.19525,17584.264,...,80.0,3.00,4.0,6.00,93.00,128.0,206.50,not_mine,None,0
4525,2293,1176-csves/0.csv,144,TCP,UDP,NaN,0.00000,0.0000,0.41100,468.635,...,1900.0,1.00,1.0,2.00,32.00,32.0,64.00,not_mine,None,0
3481,1249,642-csves/1.csv,433,TCP,UDP,NaN,0.00000,4.9090,17.33600,7329.074,...,37046.0,1.00,4.0,11.00,64.00,159.0,2146.00,not_mine,None,0
4694,2462,1264-csves/0.csv,457,TCP,UDP,NaN,0.00000,0.0720,30.73000,10298.692,...,123.0,1.00,3.0,14.00,48.00,191.0,3177.00,not_mine,None,0
1882,801,78-csves/4.csv,16,TCP,NaN,NaN,4.05400,32.6855,47.45150,528.592,...,NaN,3.75,20.5,30.00,494.25,1188.5,4590.25,mine,Etherium,4
4484,2252,1155-csves/1.csv,288,TCP,UDP,NaN,0.00000,0.0000,0.94350,3234.260,...,80.0,1.00,1.0,9.00,32.00,40.0,858.00,not_mine,None,0
2740,508,261-csves/1.csv,18,TCP,UDP,NaN,0.00725,0.2130,57.83050,353.355,...,1900.0,3.00,3.5,5.00,96.00,152.0,300.75,not_mine,None,0
711,464,75-csves/5.csv,2,TCP,NaN,NaN,246.49250,246.4930,246.49350,492.986,...,NaN,12.00,12.0,12.00,3135.00,6030.0,8925.00,mine,Bitcash,2
403,156,25-csves/7.csv,2,TCP,NaN,NaN,524.04625,524.0465,524.04675,1048.093,...,NaN,21.00,21.0,21.00,5129.25,9838.5,14547.75,mine,Bitcash,2
4271,2039,1046-csves/0.csv,48,TCP,UDP,NaN,0.00000,43.5520,104.23575,2817.922,...,80.0,1.00,4.0,5.25,48.00,156.0,248.00,not_mine,None,0
2455,223,115-csves/0.csv,137,TCP,UDP,NaN,0.21100,3.8710,21.74100,2441.807,...,53.0,2.00,4.0,8.00,64.00,100.0,862.00,not_mine,None,0
2888,656,337-csves/0.csv,127,TCP,UDP,NaN,14.05850,45.1040,90.11200,6486.917,...,123.0,2.00,3.0,4.00,64.00,96.0,128.00,not_mine,None,0
1645,564,35-csves/5.csv,8,TCP,NaN,NaN,16.22075,25.0355,37.56200,247.977,...,NaN,8.00,13.0,22.00,807.25,1813.0,2402.75,mine,Etherium,4
3673,1441,740-csves/0.csv,100,TCP,UDP,NaN,0.00000,41.2355,50.11000,3037.620,...,1900.0,1.00,2.0,3.00,39.75,60.0,104.00,not_mine,None,0
659,412,67-csves/3.csv,2,TCP,NaN,NaN,548.73775,548.7385,548.73925,1097.477,...,NaN,33.00,33.0,33.00,9182.25,17704.5,26226.75,mine,Bitcash,2
3184,952,490-csves/0.csv,74,TCP,UDP,NaN,14.34325,116.5320,198.47775,8421.001,...,1900.0,4.25,6.0,12.75,165.00,340.0,1317.00,not_mine,None,0
108,108,18-csves/0.csv,4,TCP,NaN,NaN,244.49175,245.3205,246.14900,981.281,...,52072.0,18.00,18.0,19.75,518.00,7047.5,14112.50,mine,Bitcoin,1
2001,920,99-csves/0.csv,13,TCP,NaN,NaN,20.27800,43.6150,59.15800,851.330,...,NaN,10.00,23.0,35.00,994.00,1997.0,7253.00,mine,Etherium,4
684,437,70-csves/8.csv,2,TCP,NaN,NaN,545.85150,545.8520,545.85250,1091.704,...,NaN,35.50,36.0,36.50,9446.75,17943.5,26440.25,mine,Bitcash,2
1246,165,7-csves/23.csv,12,TCP,NaN,NaN,39.44100,45.8345,56.30525,558.867,...,NaN,22.75,30.5,34.00,1274.25,1814.5,6484.75,mine,Etherium,4
243,243,40-csves/2.csv,2,TCP,NaN,NaN,212.55150,212.5590,212.56650,425.118,...,NaN,13.75,14.5,15.25,3371.00,6482.0,9593.00,mine,Bitcoin,1
3754,1522,782-csves/1.csv,390,TCP,UDP,NaN,0.00000,0.0000,6.38425,4654.402,...,123.0,1.00,1.0,5.75,32.00,48.0,340.75,not_mine,None,0
902,170,37-csves/5.csv,2,TCP,NaN,NaN,269.78100,269.7810,269.78100,539.562,...,NaN,18.25,18.5,18.75,4180.00,7874.0,11568.00,mine,Litecoin,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3912,1680,862-csves/1.csv,50,TCP,UDP,NaN,58.12500,58.6210,90.13825,3298.879,...,1900.0,3.00,4.0,5.00,96.00,144.0,216.00,not_mine,None,0
1308,227,8-csves/47.csv,10,TCP,NaN,NaN,20.57000,22.8750,61.56400,545.977,...,NaN,10.75,13.5,32.75,915.75,2144.0,3751.75,mine,Etherium,4
959,227,49-csves/5.csv,2,TCP,NaN,NaN,238.44500,238.4450,238.44500,476.890,...,NaN,19.25,20.5,21.75,4154.75,7319.5,10484.25,mine,Litecoin,3
1361,280,10-csves/24.csv,8,TCP,NaN,NaN,33.13550,48.6910,77.50500,490.464,...,NaN,17.50,24.5,40.25,1407.75,2683.5,5529.25,mine,Etherium,4
2341,109,57-csves/1.csv,281,TCP,UDP,NaN,13.88500,180.4510,228.88400,39969.991,...,1900.0,11.00,20.0,33.00,1740.00,3442.0,7920.00,not_mine,None,0
2667,435,223-csves/0.csv,45,TCP,UDP,NaN,166.10100,239.6160,241.66400,8890.174,...,1900.0,7.00,8.0,12.00,224.00,256.0,853.00,not_mine,None,0
1926,845,86-csves/1.csv,14,TCP,NaN,NaN,5.45725,24.4960,45.06150,421.251,...,NaN,4.00,14.5,25.75,690.75,867.5,3057.25,mine,Etherium,4
2503,271,139-csves/1.csv,158,TCP,UDP,NaN,0.00000,13.6375,46.20475,4350.368,...,1900.0,1.00,3.0,7.00,41.75,96.0,756.00,not_mine,None,0
4221,1989,1020-csves/1.csv,75,TCP,UDP,NaN,45.07650,46.0500,47.00150,3350.339,...,53.0,2.00,2.0,5.00,64.00,64.0,703.50,not_mine,None,0
551,304,50-csves/5.csv,2,TCP,NaN,NaN,578.47400,578.4740,578.47400,1156.948,...,NaN,23.00,23.0,23.00,5396.50,10333.0,15269.50,mine,Bitcash,2
4680,2448,1257-csves/0.csv,258,TCP,UDP,NaN,0.00000,0.8400,18.39950,2429.093,...,1900.0,1.00,3.0,7.75,48.00,91.5,994.50,not_mine,None,0
2684,452,232-csves/0.csv,81,UDP,TCP,NaN,0.00000,0.0000,0.95100,94.818,...,60786.0,1.00,1.0,10.00,37.00,120.0,922.00,not_mine,None,0
231,231,38-csves/2.csv,6,TCP,NaN,NaN,124.01025,242.7005,244.70425,1145.010,...,52781.0,13.25,17.0,23.75,498.00,3429.0,13486.50,mine,Bitcoin,1
1904,823,82-csves/3.csv,2,TCP,NaN,NaN,298.61600,298.6160,298.61600,597.232,...,NaN,178.75,184.5,190.25,16767.50,25168.0,33568.50,mine,Etherium,4
3454,1222,628-csves/1.csv,221,TCP,UDP,NaN,0.00000,0.1060,29.97600,3691.710,...,1900.0,1.00,2.0,4.00,32.00,48.0,128.00,not_mine,None,0
2014,933,101-csves/2.csv,2,TCP,NaN,NaN,296.90200,296.9020,296.90200,593.804,...,NaN,187.75,192.5,197.25,17288.50,26090.0,34891.50,mine,Etherium,4
1174,93,5-csves/40.csv,4,TCP,NaN,NaN,72.53600,159.4815,246.66375,638.873,...,NaN,45.50,88.5,135.00,5531.50,8286.0,15234.50,mine,Etherium,4
2931,699,358-csves/1.csv,57,TCP,UDP,NaN,0.00000,1.0240,18.10200,631.461,...,5355.0,1.00,3.0,10.00,55.00,156.0,2227.00,not_mine,None,0
2342,110,58-csves/0.csv,112,TCP,UDP,NaN,0.00000,0.1375,11.97375,926.510,...,1900.0,1.00,5.0,8.00,81.25,713.0,2897.00,not_mine,None,0
544,297,49-csves/6.csv,2,TCP,NaN,NaN,449.43950,463.6600,477.88050,927.320,...,NaN,24.25,24.5,24.75,6285.00,12070.0,17855.00,mine,Bitcash,2
2175,135,39-csves/1.csv,2,TCP,NaN,NaN,564.13225,564.1325,564.13275,1128.265,...,NaN,16.00,16.0,16.00,1335.50,2011.0,2686.50,mine,Monero,5
4236,2004,1028-csves/0.csv,47,TCP,UDP,NaN,24.29600,102.9620,104.54350,3797.709,...,80.0,3.00,4.0,6.00,84.00,128.0,248.00,not_mine,None,0
2231,191,54-csves/4.csv,2,TCP,NaN,NaN,526.82200,526.8230,526.82400,1053.646,...,NaN,13.00,13.0,13.00,1049.75,1839.5,2629.25,mine,Monero,5
4005,1773,910-csves/0.csv,221,TCP,UDP,NaN,0.00000,0.4090,13.98600,3163.029,...,80.0,1.00,2.0,3.00,32.00,48.0,128.00,not_mine,None,0
1524,443,14-csves/35.csv,32,TCP,NaN,NaN,3.98300,16.2405,22.85325,504.958,...,58839.0,4.75,10.5,14.25,383.75,673.0,2266.00,mine,Etherium,4
2368,136,71-csves/0.csv,28,TCP,UDP,NaN,58.40550,90.1120,103.68150,2205.314,...,51632.0,3.00,5.0,5.00,60.00,160.0,216.00,not_mine,None,0
91,91,15-csves/1.csv,2,TCP,NaN,NaN,217.46275,217.4805,217.49825,434.961,...,NaN,10.00,10.0,10.00,2667.75,5135.5,7603.25,mine,Bitcoin,1
2558,326,167-csves/1.csv,77,UDP,TCP,NaN,0.00000,0.0800,73.71900,3213.394,...,123.0,1.00,2.0,5.00,48.00,89.0,348.00,not_mine,None,0
2334,102,54-csves/0.csv,464,TCP,UDP,NaN,0.00000,0.3280,45.05600,9704.986,...,80.0,1.00,2.0,9.00,32.75,68.0,1559.00,not_mine,None,0
3671,1439,739-csves/0.csv,4,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,...,38900.0,1.00,1.0,1.00,33.75,51.0,70.25,not_mine,None,0

In [24]:
pure_data_miner.columns

Index(['index', 'Name', 'Netflows', 'First_Protocol', 'Second_Protocol',
       'Third_Protocol', 'p1_d', 'p2_d', 'p3_d', 'duration', 'max_d', 'min_d',
       '#packets', 'Avg_bps', 'Avg_pps', 'Avg_bpp', '#Bytes', '#sp', '#dp',
       'first_sp', 'second_sp', 'third_sp', 'first_dp', 'second_dp',
       'third_dp', 'p1_ip', 'p2_ip', 'p3_ip', 'p1_ib', 'p2_ib', 'p3_ib',
       'Type', 'Cryptocurrency', 'Id_Cryptocurrency'],
      dtype='object')

In [25]:
new_names = ['index','Name','N_Netflows','First_Protocol','Second_Protocol','Third_Protocol','Q1_Duration','Q2_Duration','Q3_Duration','Duration','Max_Duration','Min_Duration','N_Packets','Avg_BitsXSecond', 'Avg_PacketsXSecond', 'Avg_BytesXSecond', 'N_Bytes', 'N_Source_Port','N_Desti_Port','First_Src_Top','Second_Src_Top','Third_Src_Top', 'First_Dest_Top','Second_Dest_Top','Third_Dest_Top','Q1_Package','Q2_Package','Q3_Package','Q1_Bytes','Q2_Bytes','Q3_Bytes','Type','Cryptocurrency','Id_Cryptocurrency']             
len(new_names)

34

In [26]:
# Guarde nuestro conjunto de datos 
pure_data_miner.to_csv('dataC.csv', index=False)

### Estructuración data benigna con data minera no identificada

In [27]:
not_pure_data_miner = pd.concat([sinclasificar,benignoAlexa], axis=0)
not_pure_data_miner

,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,max_d,...,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type,Cryptocurrency,Id_Cryptocurrency
0,0-csves/0.csv,1564,TCP,UDP,ICMP,0.00000,0.1010,1.72100,10701.930,177.706,...,80.0,1.00,2.0,16.00,40.00,115.5,1883.50,mine,Unclassified,6
1,0-csves/1.csv,50572,TCP,UDP,NaN,0.12000,0.1210,0.12400,11602.090,55.906,...,80.0,2.00,2.0,2.00,40.00,63.0,88.00,mine,Unclassified,6
2,1-csves/0.csv,2,TCP,NaN,NaN,366.69000,366.7300,366.77000,733.460,366.810,...,NaN,30.00,33.0,36.00,3988.00,5962.0,7936.00,mine,Unclassified,6
3,1-csves/1.csv,20,TCP,UDP,NaN,0.00000,4.1530,7.70100,86.786,12.255,...,62357.0,1.00,12.5,17.50,50.75,798.0,7411.50,mine,Unclassified,6
4,2-csves/0.csv,322,TCP,UDP,NaN,0.00000,1.9585,27.59625,6541.874,303.171,...,53.0,1.00,5.0,11.00,50.00,316.0,2281.25,mine,Unclassified,6
5,2-csves/2.csv,152,UDP,TCP,NaN,0.00000,0.0000,0.81800,740.146,105.354,...,59140.0,1.00,1.0,3.00,40.00,99.0,217.50,mine,Unclassified,6
6,3-csves/0.csv,12,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,60314.0,1.00,1.0,1.00,38.50,124.5,203.00,mine,Unclassified,6
7,3-csves/1.csv,332,UDP,TCP,NaN,0.09700,0.4120,1.53600,3162.308,217.804,...,137.0,2.00,2.0,6.00,48.00,92.0,858.00,mine,Unclassified,6
8,4-csves/1.csv,32,TCP,NaN,NaN,0.06100,3.6860,30.51725,451.303,44.918,...,34762.0,2.75,10.0,14.25,232.75,1517.5,5742.75,mine,Unclassified,6
9,5-csves/0.csv,2,TCP,NaN,NaN,343.84850,343.8740,343.89950,687.748,343.925,...,NaN,19.50,21.0,22.50,1849.00,2606.0,3363.00,mine,Unclassified,6
10,5-csves/1.csv,23,TCP,UDP,NaN,0.00000,0.7660,7.62100,81.816,12.255,...,49274.0,1.00,12.0,16.00,49.50,808.0,5937.00,mine,Unclassified,6
11,6-csves/0.csv,6,TCP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,49539.0,1.00,1.0,1.00,20.00,20.0,20.00,mine,Unclassified,6
12,6-csves/1.csv,16,TCP,UDP,NaN,0.00000,10.2660,27.38450,235.194,41.421,...,58100.0,1.00,7.0,20.50,265.50,946.5,2225.75,mine,Unclassified,6
13,7-csves/0.csv,10,TCP,UDP,NaN,0.29675,1.1135,2.08575,131.563,62.855,...,49338.0,3.00,4.5,27.00,384.50,1260.5,2442.50,mine,Unclassified,6
14,7-csves/1.csv,14,TCP,UDP,NaN,0.00000,0.0000,0.26250,12.068,5.613,...,61597.0,1.00,1.0,5.00,30.00,37.0,263.00,mine,Unclassified,6
15,7-csves/2.csv,14,TCP,UDP,NaN,0.14900,0.2420,0.31025,83.882,40.833,...,53.0,4.25,5.0,6.00,227.00,275.0,295.00,mine,Unclassified,6
16,7-csves/3.csv,24,TCP,UDP,NaN,0.00000,0.1815,8.02825,265.087,88.007,...,80.0,1.00,5.0,5.00,165.25,295.0,361.00,mine,Unclassified,6
17,8-csves/0.csv,38577,UDP,TCP,NaN,0.00000,0.0000,0.00000,4473.860,56.974,...,80.0,1.00,1.0,1.00,26.00,26.0,26.00,mine,Unclassified,6
18,8-csves/1.csv,2,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,NaN,1.00,1.0,1.00,45.00,53.0,61.00,mine,Unclassified,6
19,9-csves/0.csv,14,TCP,NaN,NaN,0.40825,51.8640,112.98275,786.133,120.108,...,49441.0,1.25,7.5,178.25,25.00,895.0,30283.75,mine,Unclassified,6
20,9-csves/1.csv,8,TCP,NaN,NaN,1.30950,1.8075,2.82200,18.371,5.250,...,49435.0,5.50,6.5,18.50,725.00,1415.0,1906.75,mine,Unclassified,6
21,10-csves/0.csv,1,UDP,NaN,NaN,8.48400,8.4840,8.48400,8.484,8.484,...,NaN,18.00,18.0,18.00,8625.00,8625.0,8625.00,mine,Unclassified,6
22,10-csves/1.csv,3,TCP,UDP,NaN,132.67450,256.9120,256.91250,522.262,256.913,...,9000.0,14.00,17.0,17.50,3317.50,6410.0,7517.50,mine,Unclassified,6
23,10-csves/2.csv,1,UDP,NaN,NaN,8.43800,8.4380,8.43800,8.438,8.438,...,NaN,18.00,18.0,18.00,8625.00,8625.0,8625.00,mine,Unclassified,6
24,10-csves/3.csv,5,UDP,TCP,NaN,0.00000,0.0000,264.63100,529.362,264.731,...,1099.0,1.00,1.0,13.00,300.00,301.0,368.00,mine,Unclassified,6
25,10-csves/4.csv,8,TCP,UDP,NaN,38.36100,91.4105,142.51550,790.927,220.620,...,1900.0,4.50,7.0,8.50,132.75,2194.0,3952.25,mine,Unclassified,6
26,10-csves/5.csv,3,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,NaN,1.00,1.0,1.00,300.00,300.0,300.50,mine,Unclassified,6
27,10-csves/6.csv,6,UDP,TCP,NaN,0.00000,7.5245,287.75275,772.357,378.654,...,1099.0,1.00,3.5,12.00,300.00,300.5,673.75,mine,Unclassified,6
28,10-csves/7.csv,4,UDP,TCP,NaN,0.00000,276.0675,552.13525,1104.271,552.136,...,1099.0,1.00,11.0,23.75,300.75,417.5,3723.00,mine,Unclassified,6
29,10-csves/8.csv,2,UDP,NaN,NaN,2.10925,4.2185,6.32775,8.437,8.437,...,NaN,5.25,9.5,13.75,2381.25,4462.5,6543.75,mine,Unclassified,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2471,1268-csves/1.csv,49,TCP,UDP,NaN,0.00000,0.0000,0.58800,185.244,44.800,...,53.0,1.00,1.0,3.00,20.00,37.0,100.00,not_mine,None,0
2472,1269-csves/0.csv,265,TCP,UDP,NaN,0.00000,0.6030,118.57900,12788.381,241.461,...,123.0,1.00,3.0,7.00,48.00,183.0,375.00,not_mine,None,0
2473,1269-csves/1.csv,16,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,60123.0,1.00,1.0,1.00,37.00,48.5,77.50,not_mine,None,0
2474,1270-csves/1.csv,465,TCP,UDP,NaN,0.00000,0.0000,13.44400,6049.491,120.005,...,80.0,1.00,1.0,3.00,32.00,32.0,127.00,not_mine,None,0
2475,1271-csves/0.csv,514,TCP,UDP,NaN,0.00000,0.0000,2.44050,4811.240,80.005,...,1900.0,1.00,1.0,4.00,32.00,32.0,375.00,not_mine,None,0
2476,1271-csves/1.csv,88,TCP,UDP,NaN,10.80750,14.2645,45.05600,2202.095,60.018,...,80.0,2.00,2.0,4.00,64.00,64.0,184.00,not_mine,None,0
2477,1272-csves/0.csv,38,TCP,UDP,NaN,0.29150,141.5590,168.83175,4614.424,289.849,...,443.0,4.00,7.0,23.50,92.00,267.5,3063.75,not_mine,None,0
2478,1272-csves/1.csv,24,UDP,TCP,NaN,0.00000,0.0020,0.59600,67.783,60.011,...,53.0,1.00,3.0,3.00,48.00,111.5,375.00,not_mine,None,0
2479,1273-csves/0.csv,142,TCP,UDP,NaN,0.00000,0.0000,1.03800,1049.615,60.251,...,1900.0,1.00,1.0,5.75,32.00,32.0,808.00,not_mine,None,0
2480,1273-csves/1.csv,67,TCP,UDP,NaN,0.00000,103.4610,127.58600,4873.085,150.016,...,80.0,2.50,4.0,6.00,64.00,128.0,232.00,not_mine,None,0
2481,1274-csves/0.csv,196,TCP,UDP,NaN,68.97325,148.3060,180.25450,24152.677,194.928,...,80.0,4.00,5.0,6.00,80.00,160.0,192.00,not_mine,None,0
2482,1274-csves/1.csv,555,TCP,UDP,NaN,0.00000,0.6270,46.32200,11400.446,75.725,...,80.0,1.00,7.0,17.00,42.00,736.0,5027.50,not_mine,None,0
2483,1275-csves/0.csv,76,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,34433.0,1.00,1.0,1.00,35.00,46.0,80.75,not_mine,None,0
2484,1275-csves/1.csv,358,TCP,UDP,NaN,0.98250,19.7645,63.03200,15948.270,194.951,...,80.0,5.00,7.0,13.00,192.00,923.0,3814.50,not_mine,None,0
2485,1276-csves/0.csv,95,TCP,UDP,NaN,0.00000,48.1550,169.49700,8336.335,245.582,...,80.0,1.00,4.0,14.50,48.00,171.0,737.50,not_mine,None,0
2486,1276-csves/1.csv,6,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,52061.0,1.00,1.0,1.00,33.75,81.0,130.50,not_mine,None,0
2487,1277-csves/0.csv,189,TCP,UDP,ICMP6,0.00000,5.6180,9.97000,2526.679,133.972,...,123.0,1.00,7.0,10.00,94.00,610.0,1448.00,not_mine,None,0
2488,1277-csves/1.csv,129,TCP,UDP,NaN,9.81900,171.8840,240.06800,16951.077,242.080,...,1900.0,7.00,10.0,23.00,319.00,1079.0,3011.00,not_mine,None,0
2489,1278-csves/0.csv,126,TCP,UDP,NaN,0.00000,0.1340,2.50050,905.539,65.475,...,123.0,1.00,4.0,8.00,48.00,678.5,2853.00,not_mine,None,0
2490,1278-csves/1.csv,53,TCP,UDP,NaN,180.19800,240.0080,246.19300,10391.339,296.575,...,1900.0,11.00,26.0,43.00,696.00,3882.0,13042.00,not_mine,None,0
2491,1279-csves/0.csv,61,TCP,UDP,NaN,0.00000,3.0200,20.01200,960.849,92.077,...,123.0,1.00,2.0,4.00,48.00,64.0,696.00,not_mine,None,0
2492,1279-csves/1.csv,37,TCP,UDP,NaN,0.63500,103.0560,121.87400,2970.071,180.992,...,443.0,3.00,4.0,5.00,60.00,160.0,248.00,not_mine,None,0
2493,1280-csves/0.csv,184,TCP,UDP,NaN,0.00000,0.0030,45.06250,3600.671,92.112,...,80.0,1.00,2.0,4.00,40.00,64.0,144.75,not_mine,None,0
2494,1280-csves/1.csv,257,TCP,UDP,NaN,0.00000,0.0000,45.05200,3475.801,71.680,...,53.0,1.00,1.0,3.00,32.00,47.0,167.00,not_mine,None,0
2495,1281-csves/0.csv,71,TCP,UDP,NaN,0.00000,23.7780,65.74250,2448.936,91.616,...,123.0,1.00,3.0,6.00,48.00,96.0,246.00,not_mine,None,0
2496,1281-csves/1.csv,33,TCP,UDP,NaN,3.00200,58.3480,75.77700,1956.135,149.117,...,1900.0,3.00,4.0,5.00,84.00,128.0,216.00,not_mine,None,0
2497,1282-csves/0.csv,81,TCP,UDP,NaN,0.00000,0.0000,1.00000,418.609,62.536,...,53.0,1.00,1.0,4.00,32.00,39.0,696.00,not_mine,None,0
2498,1282-csves/1.csv,66,TCP,UDP,NaN,12.16525,120.9770,149.62975,6818.819,204.810,...,80.0,3.00,4.0,5.75,80.00,122.0,216.00,not_mine,None,0
2499,1283-csves/0.csv,214,TCP,UDP,NaN,0.00000,0.0000,45.05600,3368.551,60.004,...,1900.0,1.00,1.0,2.00,32.00,40.0,64.00,not_mine,None,0
2500,1283-csves/1.csv,2,UDP,NaN,NaN,0.00000,0.0000,0.00000,0.000,0.000,...,NaN,1.00,1.0,1.00,73.00,105.0,137.00,not_mine,None,0

In [28]:
# Resetie los indices del dataframe, para que no apunte un mismo indice a varios registros
not_pure_data_miner = not_pure_data_miner.reset_index()

In [29]:
indices = list(not_pure_data_miner.index)
import random
# El rango de valores se le aplico aleatoriedad de manera pseudoaleatorio
random.shuffle(indices)

In [30]:
not_pure_data_miner = not_pure_data_miner.reindex(indices)
not_pure_data_miner.head()

,index,Name,Netflows,First_Protocol,Second_Protocol,Third_Protocol,p1_d,p2_d,p3_d,duration,...,third_dp,p1_ip,p2_ip,p3_ip,p1_ib,p2_ib,p3_ib,Type,Cryptocurrency,Id_Cryptocurrency
32479,32479,20-csves/4640.csv,14,ICMP6,NaN,NaN,0.0,0.0,0.0000,0.000,...,NaN,1.0,1.0,1.0,32.0,32.0,32.0,mine,Unclassified,6
19615,19615,19-csves/1964.csv,32,ICMP6,UDP,ICMP,0.0,0.0,3.0025,1281.235,...,1281.0,1.0,1.0,4.0,32.0,40.0,505.0,mine,Unclassified,6
5707,5707,17-csves/691.csv,32,ICMP6,ICMP,TCP,0.0,0.0,0.0000,45.014,...,1281.0,1.0,1.0,1.0,32.0,32.0,52.0,mine,Unclassified,6
26704,26704,19-csves/9053.csv,22,ICMP6,ICMP,TCP,0.0,0.0,0.0000,689.299,...,3333.0,1.0,1.0,1.0,32.0,32.0,40.0,mine,Unclassified,6
93,93,15-csves/37.csv,1,ICMP6,NaN,NaN,0.0,0.0,0.0000,0.000,...,NaN,1.0,1.0,1.0,144.0,144.0,144.0,mine,Unclassified,6

In [31]:
not_pure_data_miner.to_csv('dataD.csv',index=False)